### ISSUE TITLE
abou attention weight

### ISSUE THREAD

**Issue by laowangball** [yuquanle/Sentence-similarity-modeling#3]
sir,can you provide a copy of the code about attenion weight?

**Comment by yuquanle** [comment]
In this experiment, I use the TF-IDF to generate the attention weights(view each sentence as a document).

**Comment by laowangball** [comment]
Thank you




On 10/24/2018 00:26, yuquanle wrote:

In this experiment, I use the TF-IDF to generate the attention weights(view each sentence as a document).
