### ISSUE TITLE
Preprocessing file missing.

### ISSUE THREAD

**Issue by vikas-baghel** [yuquanle/Sentence-similarity-modeling#4]

**Comment by vikas-baghel** [comment]
How to preprocess the dataset into ACV tree format. Can you share the code/process of doing it.

**Comment by yuquanle** [comment]
Dear vikas-baghel,

     you can implement ACV-tree by using the Stanford Parser to generate the constituency tree of the sentence, and then attach the word vectors and the attention weights to the words in leaf nodes.

Best,
yuquanle

**Comment by vikas-baghel** [comment]
But in the preprocessed file that you gave in repository have contituency trees with some words missing. How you decided which words to keep and which to drop?

**Comment by yuquanle** [comment]
The stop words are removed.
